export const surpriseMePrompts = [
    'A serene forest clearing with a babbling brook.',
    'An abandoned city with overgrown vines and cracked pavement.',
    'A futuristic metropolis with flying cars and towering skyscrapers.',
    'A peaceful beach with crystal clear waters and palm trees.',
    'An alien landscape with strange plants and a glowing sky.',
    'A medieval castle with a moat and drawbridge.',
    'A post-apocalyptic wasteland with ruined buildings and a blood-red sky.',
    'A bustling market with colorful stalls and exotic goods.',
    'A magical forest with talking animals and enchanted trees.',
    'A frozen tundra with icy mountains and a shimmering aurora borealis.',
    'A mystical cave with glowing crystals and a hidden treasure.',
    'A haunted house with creaky floors and ghostly apparitions.',
    'A tropical rainforest with a rushing waterfall and colorful birds.',
    'An underwater world with schools of fish and coral reefs.',
    'A space station with high-tech equipment and a view of the Earth.',
    'A vast desert with sand dunes and a scorching sun.',
    'A colorful carnival with rides and games.',
    'A peaceful countryside with rolling hills and grazing livestock.',
    'A surreal dreamscape with floating objects and distorted perspectives.',
    'A busy city street with bustling traffic and towering skyscrapers.',
]