import { useEffect, useState } from 'react';

import { usePosts, useSearch } from '../hooks';
import { Card, Loader, SearchField } from '../components';


const RenderCards = ({ data, title }) => {

    if (data?.length > 0) return data.map(post => <Card key={post._id} {...post} />);

    return (
        <h2 className="mt-5 font-bold text-[#6469FF] text-xl uppercase">{title}</h2>
    )
}

export const HomePage = () => {

    const [posts, setPosts] = useState();
    const { startLoadingPosts, loading } = usePosts();
    const { searchTerm, searchResult, onInputSearchChange } = useSearch('', posts);

    useEffect(() => {

        const getAllPosts = async () => {
            const data = await startLoadingPosts()
            setPosts(data.reverse());
        }

        getAllPosts();

    }, []);

    return (
        <section className="max-w-7xl h-[calc(100vh-100px)] px-5 mx-auto">
            <h2 className="mb-2 text-3xl font-semibold">
                The Community Showcase
            </h2>
            <p className="text-sm text-gray-500">
                Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
            </p>

            <SearchField searchTerm={searchTerm} onInputChange={onInputSearchChange} />

            <main>
                {loading ? (
                    <div className="flex items-center justify-center">
                        <Loader />
                    </div>
                )
                    :
                    <>
                        {searchTerm && (
                            <h2 className="mb-2 text-3xl font-semibold">
                                Showing results for {searchTerm}
                            </h2>
                        )}
                        <div className="grid grid-cols-1 gap-3 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2">
                            {searchTerm
                                ? <RenderCards data={searchResult} title="No Posts Found" />
                                : <RenderCards data={posts} title="No Posts Found" />
                            }
                        </div>
                    </>
                }
            </main>

        </section>
    )
}